### ISSUE TITLE
the R package 'littler' inherited from rocker/hadleyverse repo had a bug that won't run installGithub.r correctly

### ISSUE THREAD

**Issue by lmendezboo** [OHDSI/Broadsea-MethodsLibrary#2]
the bug is discused and fixed here:
https://github.com/eddelbuettel/littler/pull/49/commits/4a5a4014714d8727b2699db96f6e42ebeb34bd3f

the thing is rocker/hadlyeverse is phasing out and mostly unmantained (latest build 9 months ago), also  it got built against an old R, namely R 3.4.1 if I recall correctly.

so even though littler bug is now corrected at CRAN a year ago, rocker/hadleyverse ignores that.

I rewrote your Dockerfile to base it on rocker/tidyverse (the one recommended by rocker to substitute hadleyverse) to fix that
plus added installation of  openjdk-8 (to automate java installation) and other required packages such as lzma and bz2 and did a javareconf at step 1.

I tested Achilles, SqlRender and DatabaseConnector (the ones depending on JAVA) from the Rstudio that offers the OHDSI/broadsea docker-compose.yml and they all work against my PostgreSQL CDM backend

lastly I commented these lines
```
## COPY Rserv.conf /etc/Rserv.conf
## COPY startRserve.R /usr/local/bin/startRserve.R
```
they complain since it does'nt find them in order to copy them, I assume it is expecting them on the host machine, I haven't tested if Rserve works as expected.

hope it helps others, thanks.

```
FROM rocker/tidyverse:latest
MAINTAINER Marc A. Suchard <msuchard@ucla.edu>

RUN apt-get update && apt-get install -y python-dev openjdk-8-jdk liblzma-dev libbz2-dev \
&& R CMD javareconf

## Install Rserve
RUN install2.r \
        Rserve \
        RSclient \
        openssl \
        httr \
        xml2 \
        remotes \
&& rm -rf /tmp/download_packages/ /tmp/*.rds


## Install OHDSI R packages
RUN installGithub.r \
        OHDSI/SqlRender \
        OHDSI/DatabaseConnector \
        OHDSI/Achilles \
        OHDSI/Cyclops \
        OHDSI/OhdsiRTools \
        OHDSI/FeatureExtraction \
        OHDSI/BigKnn \
        OHDSI/CohortMethod \
        OHDSI/PublicOracle \
        hadley/xml2 \
        cloudyr/aws.s3 \
        OHDSI/OhdsiSharing \
        OHDSI/StudyProtocols/TxPathways12mo \
        OHDSI/PatientLevelPrediction \
&& rm -rf /tmp/downloaded_packages/ /tmp/*.rds


## COPY Rserv.conf /etc/Rserv.conf
## COPY startRserve.R /usr/local/bin/startRserve.R

EXPOSE 8787
EXPOSE 6311

RUN apt-get update && apt-get install -y supervisor


RUN echo "" >> /etc/supervisor/conf.d/supervisord.conf \
        && echo "[supervisord]" >> /etc/supervisor/conf.d/supervisord.conf \
        && echo "nodaemon=true" >> /etc/supervisor/conf.d/supervisord.conf \
        && echo "" >> /etc/supervisor/conf.d/supervisord.conf \
        && echo "[program:Rserve]" >> /etc/supervisor/conf.d/supervisord.conf \
        && echo "command=/usr/local/bin/startRserve.R" >> /etc/supervisor/conf.d/supervisord.conf \
        && echo "" >> /etc/supervisor/conf.d/supervisord.conf \
        && echo "[program:RStudio]" >> /etc/supervisor/conf.d/supervisord.conf \
```

**Comment by leeevans** [comment]
@lmendezboo many thanks for providing the changes to replace hadleyverse with tidyverse. 
I've created the below pull request, so I'm closing this issue.

#3
